server:
  port: 8080
  address: 127.0.0.1
  servlet:
    context-path: /api
spring:
  datasource:
    url: jdbc:mysql://localhost:3310/chatmedb?createDatabaseIfNotExist=true&serverTimezone=UTC
    password: ${DB_USERNAME}
    username: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
  profiles:
    active: dev
  mvc:
    throw-exception-if-no-handler-found: true
logging:
  level:
    pl:
      chatme: debug

# Json web token properties
jwt:
  validity-time-in-seconds: 86400 #24h
  base64-secret: ${JWT_SECRET}

