server:
  port: 8080
  address: 127.0.0.1
  servlet:
    context-path: /api
spring:
  datasource:
    url: jdbc:mysql://localhost:3310/chatmedb?createDatabaseIfNotExist=true&serverTimezone=UTC
    password: ${DB_USERNAME}
    username: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate

# Json web token properties
jwt:
  exp: 3600000
  secret: ${JWT_SECRET}
  token:
    header: Authorization
    prefix: Bearer