server:
  port: 8080
  servlet:
    context-path: /api
spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}?createDatabaseIfNotExist=true&serverTimezone=UTC
    password: ${MYSQ_USERNAME}
    username: ${MYSQ_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
  profiles:
    active: dev
  mvc:
    throw-exception-if-no-handler-found: true
  messages:
    basename: i18n/messages
  task:
    execution:
      thread-name-prefix: chatme-backend-application-task-
      pool:
        core-size: 2
        max-size: 25
        queue-capacity: 10000
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
logging:
  level:
    pl:
      chatme: debug

mail:
  process-url: ${MAIL_BASE_URL}

# Json web token properties
jwt:
  validity-time-in-seconds: 86400 #24h
  base64-secret: ${JWT_SECRET}

