server:
  port: 8080
  address: 127.0.0.1
  servlet:
    context-path: /api
spring:
  datasource:
    url: jdbc:mysql://localhost:3310/chatmedb?createDatabaseIfNotExist=true&serverTimezone=UTC
    password: ${DB_USERNAME}
    username: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
  profiles:
    active: dev
  mvc:
    throw-exception-if-no-handler-found: true
  mail:
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    password: ${MAIL_PWD}
    username: ${MAIL}
logging:
  level:
    pl:
      chatme: debug

# Json web token properties
jwt:
  validity-time-in-seconds: 86400 #24h
  base64-secret: ${JWT_SECRET}

